// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using armonte_aplicacao.Data;

#nullable disable

namespace armonte_aplicacao.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260703174644_AddFaturasFornecedor")]
    partial class AddFaturasFornecedor
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("armonte_aplicacao.Models.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ProjetoObraRelacaoCustosId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProjetoObraRelacaoCustosId");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("armonte_aplicacao.Models.FaturaCliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Auto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("ClienteId")
                        .HasColumnType("int");

                    b.Property<string>("Codigo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Iva")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.Property<decimal>("ValorComIva")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ValorSemIva")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ValorTotal")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.ToTable("Fatura");
                });

            modelBuilder.Entity("armonte_aplicacao.Models.FaturaFornecedor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("FaturaAutoLiquidacao")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("FornecedorId")
                        .HasColumnType("int");

                    b.Property<decimal>("Iva")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ValorComIva")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ValorSemIva")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ValorTotal")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("FornecedorId");

                    b.ToTable("FaturaFornecedores");
                });

            modelBuilder.Entity("armonte_aplicacao.Models.Fornecedor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ObrasId")
                        .HasColumnType("int");

                    b.Property<int?>("ProjetoObraRelacaoCustosId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ObrasId");

                    b.HasIndex("ProjetoObraRelacaoCustosId");

                    b.ToTable("Fornecedores");
                });

            modelBuilder.Entity("armonte_aplicacao.Models.Obras", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Morada")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MoradaContabilistica")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProjetoId")
                        .HasColumnType("int");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProjetoId");

                    b.ToTable("Obras");
                });

            modelBuilder.Entity("armonte_aplicacao.Models.Produtos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Contabilidade")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<string>("Designacao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Existe")
                        .HasColumnType("bit");

                    b.Property<int>("FornecedorId")
                        .HasColumnType("int");

                    b.Property<decimal>("Iva")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("ObrasId")
                        .HasColumnType("int");

                    b.Property<bool>("PertenceAObra")
                        .HasColumnType("bit");

                    b.Property<decimal>("ValorComIva")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ValorSemIva")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ValorTotal")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("FornecedorId");

                    b.HasIndex("ObrasId");

                    b.ToTable("Produtos");
                });

            modelBuilder.Entity("armonte_aplicacao.Models.ProjetoObraRelacaoCustos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AnoRegularizacao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Designacao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("InicioObra")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("ProjetoObraRelacaoCustos");
                });

            modelBuilder.Entity("armonte_aplicacao.Models.Cliente", b =>
                {
                    b.HasOne("armonte_aplicacao.Models.ProjetoObraRelacaoCustos", null)
                        .WithMany("Clientes")
                        .HasForeignKey("ProjetoObraRelacaoCustosId");
                });

            modelBuilder.Entity("armonte_aplicacao.Models.FaturaCliente", b =>
                {
                    b.HasOne("armonte_aplicacao.Models.Cliente", null)
                        .WithMany("FaturasAutos")
                        .HasForeignKey("ClienteId");
                });

            modelBuilder.Entity("armonte_aplicacao.Models.FaturaFornecedor", b =>
                {
                    b.HasOne("armonte_aplicacao.Models.Fornecedor", null)
                        .WithMany("FaturasAssociadas")
                        .HasForeignKey("FornecedorId");
                });

            modelBuilder.Entity("armonte_aplicacao.Models.Fornecedor", b =>
                {
                    b.HasOne("armonte_aplicacao.Models.Obras", null)
                        .WithMany("Fornecedores")
                        .HasForeignKey("ObrasId");

                    b.HasOne("armonte_aplicacao.Models.ProjetoObraRelacaoCustos", null)
                        .WithMany("Fornecedores")
                        .HasForeignKey("ProjetoObraRelacaoCustosId");
                });

            modelBuilder.Entity("armonte_aplicacao.Models.Obras", b =>
                {
                    b.HasOne("armonte_aplicacao.Models.ProjetoObraRelacaoCustos", "Projeto")
                        .WithMany("Obras")
                        .HasForeignKey("ProjetoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Projeto");
                });

            modelBuilder.Entity("armonte_aplicacao.Models.Produtos", b =>
                {
                    b.HasOne("armonte_aplicacao.Models.Fornecedor", "Fornecedor")
                        .WithMany()
                        .HasForeignKey("FornecedorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("armonte_aplicacao.Models.Obras", null)
                        .WithMany("Constituintes")
                        .HasForeignKey("ObrasId");

                    b.Navigation("Fornecedor");
                });

            modelBuilder.Entity("armonte_aplicacao.Models.Cliente", b =>
                {
                    b.Navigation("FaturasAutos");
                });

            modelBuilder.Entity("armonte_aplicacao.Models.Fornecedor", b =>
                {
                    b.Navigation("FaturasAssociadas");
                });

            modelBuilder.Entity("armonte_aplicacao.Models.Obras", b =>
                {
                    b.Navigation("Constituintes");

                    b.Navigation("Fornecedores");
                });

            modelBuilder.Entity("armonte_aplicacao.Models.ProjetoObraRelacaoCustos", b =>
                {
                    b.Navigation("Clientes");

                    b.Navigation("Fornecedores");

                    b.Navigation("Obras");
                });
#pragma warning restore 612, 618
        }
    }
}
